CREATE SCHEMA SocialDevelop

CREATE TABLE skill (
id INTEGER NOT NULL AUTO_INCREMENT,
nome VARCHAR(50),
PRIMARY KEY(id)
);

CREATE TABLE utente (
id INTEGER NOT NULL AUTO_INCREMENT,
nome VARCHAR(20) NOT NULL,
cognome VARCHAR(20) NOT NULL,
codice_fiscale CHAR(16) NOT NULL,
residenza VARCHAR(30) NOT NULL,
email VARCHAR(30) NOT NULL,
password CHAR(32) NOT NULL,
telefono INTEGER NOT NULL,
data_nascita DATE NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE utente_skill(
id INTEGER NOT NULL AUTO_INCREMENT,
utente INTEGER NOT NULL,
skill INTEGER NOT NULL,
livello INTEGER NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(utente) REFERENCES utente(id),
FOREIGN KEY(skill) REFERENCES skill(id)
);

CREATE TABLE progetto(
id INTEGER NOT NULL AUTO_INCREMENT,
nome VARCHAR(20) NOT NULL,
descrizione VARCHAR(150),
PRIMARY KEY(id)
);

CREATE TABLE task(
id INTEGER NOT NULL AUTO_INCREMENT,
descrizione VARCHAR(100) NOT NULL,
collaboratori INTEGER NOT NULL,
data_inizio DATE NOT NULL,
data_fine DATE NOT NULL,
progetto INTEGER NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(progetto) REFERENCES progetto(id)
);

CREATE TABLE tipo(
id INTEGER NOT NULL AUTO_INCREMENT,
nome VARCHAR(20) NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE task_tipo_skill(
id INTEGER NOT NULL AUTO_INCREMENT,
task INTEGER NOT NULL,
tipo INTEGER NOT NULL,
skill INTEGER NOT NULL,
livello INTEGER NOT NULL, 
PRIMARY KEY(id),
FOREIGN KEY(task) REFERENCES task(id),
FOREIGN KEY(tipo) REFERENCES tipo(id),
FOREIGN KEY(skill) REFERENCES skill(id)
);

CREATE TABLE utente_progetto(
id INTEGER NOT NULL AUTO_INCREMENT,
utente INTEGER NOT NULL,
progetto INTEGER NOT NULL,
ruolo VARCHAR(20) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(utente) REFERENCES utente(id),
FOREIGN KEY(progetto) REFERENCES progetto(id)
);

CREATE TABLE messaggio(
id INTEGER NOT NULL AUTO_INCREMENT,
utente INTEGER NOT NULL,
progetto INTEGER NOT NULL,
testo VARCHAR(100) NOT NULL,
data DATE NOT NULL,
tipo VARCHAR(10) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(utente) REFERENCES utente(id),
FOREIGN KEY(progetto) REFERENCES progetto(id)
);

CREATE TABLE domanda(
id INTEGER NOT NULL AUTO_INCREMENT,
utente INTEGER NOT NULL,
task INTEGER NOT NULL,
data DATE NOT NULL,
stato VARCHAR(30) NOT NULL DEFAULT ‘in attesa’
PRIMARY KEY(id),
FOREIGN KEY(utente) REFERENCES utente(id),
FOREIGN KEY(task) REFERENCES task(id)
);

CREATE TABLE proposta(
id INTEGER NOT NULL AUTO_INCREMENT,
utente INTEGER NOT NULL,
task INTEGER NOT NULL,
data DATE NOT NULL,
stato VARCHAR(30) NOT NULL DEFAULT ‘in attesa’
PRIMARY KEY(id),
FOREIGN KEY(utente) REFERENCES utente(id),
FOREIGN KEY(task) REFERENCES task(id)
);
